In [ ]:
pip install git+https://github.com/thieu1995/mealpy

  Cloning https://github.com/thieu1995/mealpy to /tmp/pip-req-build-zjpb6vjz
  Running command git clone -q https://github.com/thieu1995/mealpy /tmp/pip-req-build-zjpb6vjz


In [ ]:
from mealpy.swarm_based.EHO import BaseEHO
import json 
import time
from mealpy.utils.visualize import *
import numpy as np


In [ ]:
def Fun(solution):
  list1 = [0] * data['vmcount'][0]
  val = 0.0
  #print(solution)
  #print(int(round(solution[0])))
  for i in range(solution.size):
    solution[i]=round(solution[i])
    if(round(solution[i])!=0.0):
      list1[int(round(solution[i]))-1]=list1[int(round(solution[i]))-1] + data['task'][0]/data['VM'][int(round(solution[i]))-1] 
    else:
      list1[int(round(solution[i]))]=list1[int(round(solution[i]))-1] + data['task'][0]/data['VM'][int(round(solution[i]))] 
  #print(solution)
  return max(list1) 
    
start_time = time.time()

In [ ]:
vm=5
tcount=10000
number=500
f = open('data_'+str(tcount)+"_"+str(vm)+'.json') 
data = json.load(f)  
size=number
vmcount= data['vmcount'][0]

problem_dict1 = {
    "fit_func": Fun,
    "lb": [0 for i in range(size)] ,
    "ub": [vmcount for i in range(size)],
    "minmax": "min",
    "verbose": True,
}
model1 = BaseEHO(problem_dict1, epoch=100, pop_size=100, pr=0.03)
model1.solve()

2022/05/19 10:52:33 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:52:33 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:52:33 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:52:33 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:52:33 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:52:33 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:52:33 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:52:33 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:52:33 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:52:34

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 

In [ ]:
model1.history.save_global_objectives_chart(filename="EHO_5_500/goc")
model1.history.save_local_objectives_chart(filename="EHO_5_500/loc")
model1.history.save_runtime_chart(filename="EHO_5_500/rtc")
model1.history.save_diversity_chart(filename="EHO_5_500/dc")

No handles with labels found to put in legend.


In [ ]:
vm=5
tcount=10000
number=1000
f = open('data_'+str(tcount)+"_"+str(vm)+'.json') 
data = json.load(f)  
size=number
vmcount= data['vmcount'][0]

problem_dict1 = {
    "fit_func": Fun,
    "lb": [0 for i in range(size)] ,
    "ub": [vmcount for i in range(size)],
    "minmax": "min",
    "verbose": True,
}
model2 = BaseEHO(problem_dict1, epoch=100, pop_size=100, pr=0.03)
model2.solve()

2022/05/19 10:47:10 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:47:10 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:47:10 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:47:10 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:47:10 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:47:10 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:47:12 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: >Epoch: 1, Current best: 1448.0, Global best: 1400.0, Runtime: 0.86541 seconds
2022/05/19 10:47:12 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: >Epoch: 1, Current best: 1448.0, Global best: 1400.0, Runtime: 0.86541 seconds
2022/05/19 10:47:12 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: >E

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 1.,
        1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1.,
        2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1.,
        1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1.,
        2., 

In [ ]:
model2.history.save_global_objectives_chart(filename="EHO_5_1000/goc")
model2.history.save_local_objectives_chart(filename="EHO_5_1000/loc")
model2.history.save_runtime_chart(filename="EHO_5_1000/rtc")
model2.history.save_diversity_chart(filename="EHO_5_1000/dc")

No handles with labels found to put in legend.


In [ ]:
vm=10
tcount=10000
number=500
f = open('data_'+str(tcount)+"_"+str(vm)+'.json') 
data = json.load(f)  
size=number
vmcount= data['vmcount'][0]

problem_dict1 = {
    "fit_func": Fun,
    "lb": [0 for i in range(size)] ,
    "ub": [vmcount for i in range(size)],
    "minmax": "min",
    "verbose": True,
}
model3 = BaseEHO(problem_dict1, epoch=100, pop_size=100, pr=0.03)
model3.solve()

2022/05/19 10:48:47 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:48:47 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:48:47 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:48:47 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:48:47 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:48:47 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:48:47 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:48:48 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: >Epoch: 1, Current best: 360.0, Global best: 320.0, Runtime: 0.42656 seconds
2022/05/19 10:48:48 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: >Epoch: 1, Current best: 360.0, Glob

(array([10.,  6., 10.,  0.,  3.,  5., 10., 10.,  1.,  6.,  6.,  7.,  9.,
         2.,  6.,  5.,  8.,  0.,  4.,  1.,  1.,  5.,  4.,  8.,  4.,  1.,
         6.,  2.,  8.,  1.,  2.,  2.,  7.,  9., 10.,  4., 10.,  3.,  5.,
         3.,  1.,  4.,  1.,  7.,  9.,  4.,  2.,  7.,  7.,  2.,  1.,  4.,
         9.,  9.,  4., 10.,  9.,  7., 10.,  8.,  5.,  8.,  1., 10., 10.,
         3.,  5.,  3.,  4.,  3.,  6.,  1.,  6.,  5.,  7.,  5.,  7.,  9.,
         4.,  3.,  4.,  5.,  8.,  1.,  6.,  8.,  2.,  5.,  3.,  7.,  3.,
         8., 10.,  9.,  9.,  0.,  2.,  2., 10.,  1.,  3.,  9.,  8.,  6.,
         1.,  4.,  8.,  4.,  5.,  8.,  2.,  5.,  7.,  3.,  4., 10.,  6.,
         8.,  9.,  6.,  2.,  0.,  1.,  9.,  4.,  7.,  2.,  7.,  3.,  4.,
         6.,  0.,  2.,  0.,  1.,  6.,  4.,  1.,  3., 10.,  5.,  4.,  9.,
         9.,  9.,  3.,  6.,  4.,  6.,  1.,  8.,  1.,  8.,  1.,  3.,  5.,
         8.,  6.,  9.,  7.,  0.,  4.,  9.,  5.,  8.,  1.,  9.,  0.,  1.,
        10.,  9.,  9.,  4.,  6., 10.,  6.,  1.,  9.

In [2]:
model3.history.save_global_objectives_chart(filename="EHO_10_500/goc")
model3.history.save_local_objectives_chart(filename="EHO_10_500/loc")
model3.history.save_runtime_chart(filename="EHO_10_500/rtc")
model3.history.save_diversity_chart(filename="EHO_10_500/dc")

NameError: ignored

In [ ]:
vm=10
tcount=10000
number=1000
f = open('data_'+str(tcount)+"_"+str(vm)+'.json') 
data = json.load(f)  
size=number
vmcount= data['vmcount'][0]

problem_dict1 = {
    "fit_func": Fun,
    "lb": [0 for i in range(size)] ,
    "ub": [vmcount for i in range(size)],
    "minmax": "min",
    "verbose": True,
}
model4 = BaseEHO(problem_dict1, epoch=100, pop_size=100, pr=0.03)
model4.solve()

2022/05/19 10:49:36 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:49:36 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:49:36 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:49:36 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:49:36 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:49:36 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:49:36 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:49:36 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: Solving single objective optimization problem.
2022/05/19 10:49:38 AM, INFO, mealpy.swarm_based.EHO.BaseEHO: >Epoch: 1, Current best: 712.0, Global best: 664.0, Runtime: 0.843

(array([ 4.,  9.,  7.,  6.,  0.,  9.,  6.,  4.,  1.,  8.,  9.,  3.,  3.,
         5.,  5.,  4.,  9.,  3.,  7.,  9.,  8.,  6.,  7.,  7.,  5.,  7.,
         5.,  2.,  0.,  2.,  6.,  8.,  0.,  7.,  8.,  9.,  2.,  0.,  0.,
         9.,  3.,  1.,  6.,  4.,  3.,  1.,  1.,  2.,  4.,  5.,  1.,  0.,
         8.,  4.,  1.,  8.,  6.,  9.,  2., 10.,  0.,  7.,  3., 10.,  5.,
         7.,  0.,  3.,  8.,  5.,  1.,  5.,  1.,  8.,  1.,  3.,  2.,  6.,
         5.,  2.,  4.,  9.,  1.,  2.,  8.,  5.,  4.,  1.,  7.,  5.,  5.,
         2.,  8.,  5.,  1.,  4.,  6., 10.,  2., 10.,  5.,  3.,  5.,  8.,
         5.,  1.,  7.,  6., 10.,  9.,  7.,  3.,  6.,  1.,  4.,  8.,  6.,
         3.,  3.,  3.,  5.,  3.,  8., 10., 10.,  5.,  2.,  3.,  9.,  7.,
         6.,  5.,  5.,  0.,  7.,  2.,  9.,  8.,  3.,  3.,  5.,  8.,  2.,
         6.,  5.,  6.,  8.,  8.,  5.,  1.,  4.,  8.,  3.,  5.,  5., 10.,
         0.,  4.,  7.,  9.,  8.,  8.,  6.,  5.,  6.,  1.,  1.,  7.,  1.,
         5.,  3.,  4.,  4.,  5.,  1.,  7.,  8.,  8.

In [3]:
model4.history.save_global_objectives_chart(filename="EHO_10_1000/goc")
model4.history.save_local_objectives_chart(filename="EHO_10_1000/loc")
model4.history.save_runtime_chart(filename="EHO_10_1000/rtc")
model4.history.save_diversity_chart(filename="EHO_10_1000/dc")

NameError: ignored