In [ ]:
pip install git+https://github.com/thieu1995/mealpy

  Cloning https://github.com/thieu1995/mealpy to /tmp/pip-req-build-p4c5e_rj
  Running command git clone -q https://github.com/thieu1995/mealpy /tmp/pip-req-build-p4c5e_rj


In [ ]:
from mealpy.swarm_based.PSO import BasePSO
import json 
import time
from mealpy.utils.visualize import *
import numpy as np


In [ ]:
def Fun(solution):
  list1 = [0] * data['vmcount'][0]
  val = 0.0
  #print(solution)
  #print(int(round(solution[0])))
  for i in range(solution.size):
    solution[i]=round(solution[i])
    if(round(solution[i])!=0.0):
      list1[int(round(solution[i]))-1]=list1[int(round(solution[i]))-1] + data['task'][0]/data['VM'][int(round(solution[i]))-1] 
    else:
      list1[int(round(solution[i]))]=list1[int(round(solution[i]))-1] + data['task'][0]/data['VM'][int(round(solution[i]))] 
  #print(solution)
  return max(list1) 
    
start_time = time.time()

In [ ]:
vm=5
tcount=10000
number=500
f = open('data_'+str(tcount)+"_"+str(vm)+'.json') 
data = json.load(f)  
size=number
vmcount= data['vmcount'][0]

problem_dict1 = {
    "fit_func": Fun,
    "lb": [0 for i in range(size)] ,
    "ub": [vmcount for i in range(size)],
    "minmax": "min",
    "verbose": True,
}
model1 = BasePSO(problem_dict1, epoch=100, pop_size=100, pr=0.03)
model1.solve()

2022/05/19 11:31:51 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:31:51 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:31:51 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:31:51 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:31:51 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:31:52 AM, INFO, mealpy.swarm_based.PSO.BasePSO: >Epoch: 1, Current best: 622.8571428571423, Global best: 622.8571428571423, Runtime: 0.45131 seconds
2022/05/19 11:31:52 AM, INFO, mealpy.swarm_based.PSO.BasePSO: >Epoch: 1, Current best: 622.8571428571423, Global best: 622.8571428571423, Runtime: 0.45131 seconds
2022/05/19 11:31:52 AM, INFO, mealpy.swarm_based.PSO.BasePSO: >Epoch: 1, Current best: 622.8571428571423, Global best: 622.857142

(array([3., 4., 1., 3., 3., 5., 5., 4., 3., 4., 1., 5., 4., 4., 2., 5., 4.,
        5., 2., 2., 0., 1., 0., 3., 0., 2., 5., 3., 1., 5., 0., 4., 5., 3.,
        5., 3., 0., 5., 4., 0., 2., 2., 0., 5., 0., 0., 3., 2., 1., 5., 2.,
        3., 5., 3., 4., 4., 0., 4., 4., 0., 0., 3., 5., 4., 3., 3., 3., 3.,
        3., 4., 3., 4., 0., 5., 5., 2., 4., 5., 1., 0., 1., 0., 4., 1., 1.,
        0., 0., 5., 1., 1., 0., 0., 2., 4., 5., 4., 3., 4., 4., 0., 1., 5.,
        5., 1., 1., 4., 5., 3., 0., 3., 2., 0., 4., 3., 4., 2., 2., 4., 4.,
        0., 1., 2., 1., 2., 5., 3., 5., 0., 1., 4., 4., 3., 1., 2., 0., 2.,
        3., 5., 5., 5., 1., 3., 5., 1., 3., 1., 4., 0., 0., 0., 2., 5., 5.,
        0., 3., 0., 3., 1., 4., 2., 1., 0., 5., 0., 4., 4., 4., 3., 4., 0.,
        0., 3., 0., 2., 5., 5., 1., 5., 2., 5., 4., 1., 0., 2., 1., 0., 1.,
        3., 5., 4., 3., 5., 5., 2., 3., 5., 1., 0., 5., 2., 3., 2., 0., 4.,
        1., 3., 3., 0., 3., 3., 3., 1., 5., 0., 4., 1., 0., 0., 5., 5., 5.,
        2., 

In [ ]:
model1.history.save_global_objectives_chart(filename="PSO_5_500/goc")
model1.history.save_local_objectives_chart(filename="PSO_5_500/loc")
model1.history.save_runtime_chart(filename="PSO_5_500/rtc")
model1.history.save_diversity_chart(filename="PSO_5_500/dc")

No handles with labels found to put in legend.


In [ ]:
vm=5
tcount=10000
number=1000
f = open('data_'+str(tcount)+"_"+str(vm)+'.json') 
data = json.load(f)  
size=number
vmcount= data['vmcount'][0]

problem_dict1 = {
    "fit_func": Fun,
    "lb": [0 for i in range(size)] ,
    "ub": [vmcount for i in range(size)],
    "minmax": "min",
    "verbose": True,
}
model2 = BasePSO(problem_dict1, epoch=100, pop_size=100, pr=0.03)
model2.solve()

2022/05/19 11:32:54 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:32:54 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:32:54 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:32:54 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:32:54 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:32:54 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:32:56 AM, INFO, mealpy.swarm_based.PSO.BasePSO: >Epoch: 1, Current best: 1225.1428571428548, Global best: 1225.1428571428548, Runtime: 0.83820 seconds
2022/05/19 11:32:56 AM, INFO, mealpy.swarm_based.PSO.BasePSO: >Epoch: 1, Current best: 1225.1428571428548, Global best: 1225.1428571428548, Runtime: 0.83820 seconds
2022/05/19 11:32

(array([3., 1., 4., 2., 4., 4., 0., 2., 2., 3., 4., 0., 3., 5., 5., 3., 3.,
        3., 3., 1., 5., 4., 3., 3., 4., 4., 4., 5., 4., 1., 1., 0., 1., 1.,
        0., 5., 4., 0., 1., 2., 0., 3., 0., 4., 2., 2., 5., 3., 1., 0., 4.,
        1., 0., 2., 5., 5., 1., 5., 4., 2., 2., 0., 5., 4., 4., 0., 1., 5.,
        0., 0., 5., 1., 3., 1., 4., 1., 1., 0., 3., 0., 0., 0., 5., 1., 5.,
        3., 1., 0., 1., 4., 4., 0., 0., 0., 0., 5., 0., 5., 3., 4., 4., 5.,
        1., 0., 5., 1., 5., 3., 0., 0., 0., 2., 0., 3., 1., 4., 5., 1., 2.,
        1., 0., 0., 3., 3., 4., 3., 3., 0., 4., 0., 2., 1., 5., 1., 4., 1.,
        5., 0., 3., 5., 5., 0., 3., 5., 4., 5., 4., 1., 1., 5., 4., 3., 2.,
        0., 1., 5., 0., 2., 1., 2., 0., 5., 3., 1., 3., 1., 1., 1., 0., 3.,
        1., 4., 4., 1., 3., 2., 2., 5., 5., 4., 5., 1., 5., 0., 5., 0., 0.,
        4., 3., 2., 0., 5., 0., 3., 5., 1., 0., 4., 3., 1., 2., 0., 3., 4.,
        5., 1., 4., 3., 0., 1., 0., 2., 1., 3., 5., 1., 5., 3., 5., 0., 4.,
        4., 

In [ ]:
model2.history.save_global_objectives_chart(filename="PSO_5_1000/goc")
model2.history.save_local_objectives_chart(filename="PSO_5_1000/loc")
model2.history.save_runtime_chart(filename="PSO_5_1000/rtc")
model2.history.save_diversity_chart(filename="PSO_5_1000/dc")

No handles with labels found to put in legend.


In [ ]:
vm=10
tcount=10000
number=500
f = open('data_'+str(tcount)+"_"+str(vm)+'.json') 
data = json.load(f)  
size=number
vmcount= data['vmcount'][0]

problem_dict1 = {
    "fit_func": Fun,
    "lb": [0 for i in range(size)] ,
    "ub": [vmcount for i in range(size)],
    "minmax": "min",
    "verbose": True,
}
model3 = BasePSO(problem_dict1, epoch=100, pop_size=100, pr=0.03)
model3.solve()

2022/05/19 11:34:27 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:34:27 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:34:27 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:34:27 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:34:27 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:34:27 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:34:27 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:34:28 AM, INFO, mealpy.swarm_based.PSO.BasePSO: >Epoch: 1, Current best: 314.28571428571445, Global best: 314.28571428571445, Runtime: 0.43176 seconds
2022/05/19 11:34:28 AM, INFO, mealpy.swarm_based.PSO.BasePSO: >Epoch: 1,

(array([ 0.,  5.,  5.,  7.,  4.,  0., 10.,  3.,  1.,  0.,  5.,  9., 10.,
         1.,  1.,  3.,  4.,  7.,  2., 10.,  2.,  5.,  5.,  6.,  8.,  2.,
         6.,  0.,  8.,  4.,  9.,  6.,  8.,  4.,  5.,  6.,  3.,  6.,  5.,
         2.,  0.,  7.,  7.,  9.,  5.,  1.,  5., 10.,  2.,  6.,  3., 10.,
        10.,  7.,  9.,  9.,  2.,  3.,  1.,  2., 10.,  7.,  8.,  0., 10.,
         4.,  0.,  1.,  3.,  6.,  4.,  9.,  5.,  3.,  2.,  1.,  2.,  4.,
         5.,  9.,  4.,  4.,  3.,  0.,  2.,  7.,  1.,  5.,  6.,  1.,  6.,
         9.,  7., 10.,  6.,  2.,  3.,  0.,  8.,  7.,  0.,  0.,  9.,  7.,
         5.,  7.,  4.,  5.,  6.,  4.,  4.,  8.,  1., 10.,  9.,  3.,  1.,
         6.,  5.,  1., 10.,  4.,  5., 10.,  3.,  7.,  9.,  6.,  0.,  6.,
         4.,  1.,  1.,  1.,  8.,  0.,  6.,  1.,  0., 10.,  6.,  0.,  0.,
         3.,  7.,  5.,  4.,  3.,  1., 10.,  2.,  9.,  6.,  5.,  7.,  8.,
         9.,  6.,  2.,  6., 10.,  3.,  8., 10.,  9.,  0.,  9.,  6.,  1.,
         5.,  5.,  1.,  8.,  0., 10.,  4.,  6.,  5.

In [ ]:
model3.history.save_global_objectives_chart(filename="PSO_10_500/goc")
model3.history.save_local_objectives_chart(filename="PSO_10_500/loc")
model3.history.save_runtime_chart(filename="PSO_10_500/rtc")
model3.history.save_diversity_chart(filename="PSO_10_500/dc")

No handles with labels found to put in legend.


In [ ]:
vm=10
tcount=10000
number=1000
f = open('data_'+str(tcount)+"_"+str(vm)+'.json') 
data = json.load(f)  
size=number
vmcount= data['vmcount'][0]

problem_dict1 = {
    "fit_func": Fun,
    "lb": [0 for i in range(size)] ,
    "ub": [vmcount for i in range(size)],
    "minmax": "min",
    "verbose": True,
}
model4 = BasePSO(problem_dict1, epoch=100, pop_size=100, pr=0.03)
model4.solve()

2022/05/19 11:35:16 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:35:16 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:35:16 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:35:16 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:35:16 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:35:16 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:35:16 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:35:16 AM, INFO, mealpy.swarm_based.PSO.BasePSO: Solving single objective optimization problem.
2022/05/19 11:35:18 AM, INFO, mealpy.swarm_based.PSO.BasePSO: >Epoch: 1, Current best: 605.7142857142853, Global best: 605.71428

(array([10., 10.,  6.,  6.,  8.,  9.,  5.,  0.,  9., 10.,  7.,  9.,  6.,
        10.,  6.,  1.,  5.,  4.,  1.,  0.,  0.,  0.,  6.,  8.,  5.,  7.,
        10., 10.,  2.,  9.,  3.,  8.,  4.,  6.,  0.,  7.,  7.,  0.,  0.,
        10.,  4.,  6.,  0., 10.,  6.,  5.,  0.,  5.,  5.,  4., 10.,  7.,
         4.,  4., 10.,  3.,  8.,  1.,  7.,  4.,  7.,  7.,  7.,  3.,  3.,
         0., 10.,  4.,  2.,  7.,  3.,  0., 10.,  3.,  9.,  9.,  6.,  5.,
        10.,  3.,  9.,  7.,  7.,  4.,  5., 10., 10.,  9.,  0.,  2.,  3.,
         7.,  4.,  1.,  5.,  6.,  6.,  4.,  7.,  9.,  6.,  8.,  3.,  2.,
         6.,  0.,  0.,  7.,  3.,  9.,  3.,  5.,  0.,  4.,  0.,  1.,  1.,
         3.,  7.,  0.,  8.,  7.,  4.,  7.,  2.,  7.,  6.,  8.,  2.,  0.,
         9.,  9.,  9.,  7.,  1.,  5.,  6.,  1.,  0.,  6.,  6.,  0.,  7.,
        10.,  0.,  0.,  6.,  0.,  0.,  5.,  0.,  2.,  9.,  5.,  5.,  4.,
        10.,  5.,  3.,  7.,  1., 10.,  4.,  6.,  3.,  6.,  6.,  9.,  7.,
         3., 10.,  4.,  6.,  3.,  7.,  0.,  6., 10.

In [ ]:
model4.history.save_global_objectives_chart(filename="PSO_10_1000/goc")
model4.history.save_local_objectives_chart(filename="PSO_10_1000/loc")
model4.history.save_runtime_chart(filename="PSO_10_1000/rtc")
model4.history.save_diversity_chart(filename="PSO_10_1000/dc")

No handles with labels found to put in legend.
